FROM openjdk:11-jre
MAINTAINER Erik Lumpkin "elfdude@yahoo.com"
ADD lib/hello-world-java-0.1-all.jar /app/lib/hello-world-java-0.1-all.jar
ADD scripts/hello-world-java /app/scripts/hello-world-java
EXPOSE 8080
CMD ["/app/scripts/hello-world-java"]
